# Generated by Django 3.1.4 on 2020-12-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video'),
        ),
        migrations.AlterField(
            model_name='like',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
