# Generated by Django 3.1.4 on 2020-12-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20201210_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_of_video',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
