# Generated by Django 3.1.4 on 2020-12-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_image_of_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_of_video',
            field=models.ImageField(default='static/images/default-video.jpg', upload_to='images/'),
        ),
    ]
