# Generated by Django 3.1.4 on 2020-12-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20201210_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image_of_video',
            new_name='image',
        ),
    ]
