# Generated by Django 3.1.4 on 2020-12-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20201210_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='media/images/default-video.jpg', upload_to='images/'),
        ),
    ]
