# Generated by Django 3.1.4 on 2020-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20201210_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='x'),
        ),
    ]
