# Generated by Django 3.1.4 on 2020-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20201211_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='enter video url'),
        ),
    ]
