# Generated by Django 3.1.4 on 2020-12-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_auto_20201213_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='test',
        ),
    ]
