# Generated by Django 3.1.4 on 2020-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_youtube', '0002_auto_20201213_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
